version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: bookyPostgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
volumes:
  pgdata: