apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/booky-393518/payments/production
        name: payments
        env:
          - name: KAFKA_BROKERS
            valueFrom:
              secretKeyRef:
                name: kafka
                key: brokers
          - name: KAFKA_API_KEY
            valueFrom:
              secretKeyRef:
                name: kafka
                key: apiKey
          - name: KAFKA_API_SECRET
            valueFrom:
              secretKeyRef:
                name: kafka
                key: apiSecret
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: stripe
                key: secret
