apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/booky-393518/auth/production
        name: auth
        env:
          - name: PORT
            value: '3001'
          - name: KAFKA_BROKERS
            valueFrom:
              secretKeyRef:
                name: kafka
                key: brokers
          - name: KAFKA_API_KEY
            valueFrom:
              secretKeyRef:
                name: kafka
                key: apiKey
          - name: KAFKA_API_SECRET
            valueFrom:
              secretKeyRef:
                name: kafka
                key: apiSecret
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database
                key: url
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: secret
          - name: JWT_EXPIRATION
            valueFrom:
              secretKeyRef:
                name: jwt
                key: expiration
        ports:
          - containerPort: 3001