apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/booky-393518/notifications/production
        name: notifications
        env:
          - name: GOOGLE_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: google
                key: clientId
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: google
                key: refreshToken
          - name: SMTP_USER
            valueFrom:
              secretKeyRef:
                name: smtp
                key: user
          - name: KAFKA_BROKERS
            valueFrom:
              secretKeyRef:
                name: kafka
                key: brokers
          - name: KAFKA_API_KEY
            valueFrom:
              secretKeyRef:
                name: kafka
                key: apiKey
          - name: KAFKA_API_SECRET
            valueFrom:
              secretKeyRef:
                name: kafka
                key: apiSecret