apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/booky-393518/reservations/production
        name: reservations
        env:
          - name: PORT
            value: '3009'
          - name: KAFKA_BROKERS
            valueFrom:
              secretKeyRef:
                name: kafka
                key: brokers
          - name: KAFKA_API_KEY
            valueFrom:
              secretKeyRef:
                name: kafka
                key: apiKey
          - name: KAFKA_API_SECRET
            valueFrom:
              secretKeyRef:
                name: kafka
                key: apiSecret
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database
                key: url
        ports:
          - containerPort: 3000